name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: darwin
            goarch: arm64
            name: macos-apple-silicon
            ext: ""
          - goos: darwin
            goarch: amd64
            name: macos-intel
            ext: ""
          - goos: linux
            goarch: amd64
            name: linux-x86_64
            ext: ""
          - goos: windows
            goarch: amd64
            name: windows-x86_64
            ext: .exe

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
          
      - name: Compile Binary
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o poti-${{ github.ref_name }}-${{ matrix.name }}${{ matrix.ext }} main.go
        
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: poti-${{ github.ref_name }}-${{ matrix.name }}${{ matrix.ext }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
