name: Build v0.8.0

on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: darwin
            goarch: arm64
            name: macos-apple-silicon
          - goos: darwin
            goarch: amd64
            name: macos-intel
          - goos: linux
            goarch: amd64
            name: linux-x86_64
          - goos: windows
            goarch: amd64
            name: windows-x86_64
            ext: .exe

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o poti-${{ github.ref_name }}-${{ matrix.name }}${{ matrix.ext }} main.go
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: poti-${{ github.ref_name }}-${{ matrix.name }}${{ matrix.ext }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
